### ISSUE TITLE
[feat] Manipulate image destination based on source

### ISSUE THREAD

**Issue by Woudan** [ChristofferNissen/helmper#115]
It would be useful to manipulate the image destination based on the source.

For example:

- source: docker.io
  destination: registry.local/repo/dockerhub
- source quay.io
  destination: registry.local/repo/quay

For quay.io/argoproj/argocd:v2.9.2 this would result in:
registry.local/repo/argoproj/argocd to registry.local/repo/quay/argoproj/argocd

This way we can keep the context of the registry from which the image originates from.

**Comment by ChristofferNissen** [comment]
Hey Woudan, 

Can the example at https://github.com/ChristofferNissen/helmper/blob/main/example/helmper.yaml help answer your question?
I have an example there specifically for Argocd

```yaml
- name: argo-cd
  version: 5.51.4
  repo:
    name: argo
    url: https://argoproj.github.io/argo-helm/
  images:
    exclude:
    - ref: ghcr.io/dexidp/dex
    excludeCopacetic:
    - ref: quay.io/argoproj/argocd
    modify: 
    - from: quay.io/argoproj/argocd
      to: quay.io/argoproj/argocd
    - fromValuePath: global.image.repository
      to: quay.io/argoproj/argocd
```
