### ISSUE TITLE
Unable to pull the chart from oci registry

### ISSUE THREAD

**Issue by bharathv195** [ChristofferNissen/helmper#121]
Unable to pull the helm chart while trying to pull  from the oci registry which has the repo link like "oci://ghcr.io/kube-logging/helm-charts/logging-operator" . And that helm chart does not have any repo name. we are getting the below error.

"ERROR","msg":"could not find protocol handler for: "}

**Comment by ChristofferNissen** [comment]
Can you share your config.yaml file?

**Comment by bharathv195** [comment]
```
k8s_version: 1.27.9
import:
  enabled: true
charts:
- name: ${HELM_CHART}
  version: ${REPO_VERSION}
  valuesFilePath: /workspace/in/values/prometheus/values.yaml # (Optional)
  repo:
    name: ${REPO}
    url: ${THIRDPARTY_URL}
registries:
- name: registry
  url: ${REGISTRY_URL}
  insecure: false
  plainHTTP: false
```

Hi Nissen, this is the config file we are using
