### ISSUE TITLE
Wrong versions passed to images in some cases

### ISSUE THREAD

**Issue by alexballas** [ChristofferNissen/helmper#125]
Hello, this is the helm chart I'm using

```
$ cat helmper.yaml 
k8s_version: 1.27.9
import:
  enabled: true
charts:
- name: aws-ebs-csi-driver
  version: 2.36.0
  valuesFilePath: ./values.yaml
  repo:
    name: aws-ebs-csi-driver
    url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
registries:
- name: registry
  url: h.internal.com/public
  insecure: false
  plainHTTP: false
```
If I run helmper on this I get the following error
```
{"time":"2024-10-23T15:54:21.109620637+03:00","level":"INFO","msg":"Image not available. will be excluded from import...","image":"us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:1.36.0"}
```

The version `1.36.0` in this case is wrong as helmper defaulted to the appVersion. If we inspect the `values.yaml` file here https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/values.yaml we can see that the image is comming from
```
helmTester:
  enabled: true
  # Supply a custom image to the ebs-csi-driver-test pod in helm-tester.yaml
  image: "us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20241011-e8871c079d-master"
```
where no explicit tag is defined.
In similar cases we should be extracting the tag from the image name. In this case `v20241011-e8871c079d-master`

What's your view on that?  I could propose a change handle this case.
