### ISSUE TITLE
Can't copy images to OCI repo

### ISSUE THREAD

**Issue by dazmc** [ChristofferNissen/helmper#140]
Trying to implement the  demo - the helmper configuration implies insecure and plain http - it might be me doing something wrong.

- I launch zot using podman

```
podman run -d -p 5000:5000 ghcr.io/project-zot/zot-linux-amd64:lates
```

- Then create the basic configuration and execute helmper
```
k8s_version: 1.31.1
import:
  enabled: true
charts:
- name: prometheus
  version: 25.8.0
  valuesFilePath: /workspace/in/values/prometheus/values.yaml # (Optional)
  repo:
    name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts/
registries:
- name: registry
  url: oci://0.0.0.0:5000
  insecure: true
  plainHTTP: true
```

it results in the following which complains in about http response to https client - "https://0.0.0.0:5000...." why is it trying https?

```
{"time":"2024-11-19T16:18:17.962085672Z","level":"ERROR","msg":"internal: error importing chart to registry: helm: error pushing chart kube-state-metrics to registry oci://0.0.0.0:5000 :: error pushing chart: failed to do request: Head \"https://0.0.0.0:5000/v2/charts/kube-state-metrics/blobs/sha256:98fd639856e028124519658403fcc7f4dd5cd5ca7ea874263e21a32c85c1425d\": http: server gave HTTP response to HTTPS client"}
```
