### ISSUE TITLE
Semver test tags are not downloaded

### ISSUE THREAD

**Issue by exnerd** [ChristofferNissen/helmper#147]
Hi,

I have a private gitlab registry where helm charts and images are stored. I want to copy the test version to a harbor registry.

```
 644 | Chart    | sparta | 24.16.7 | 24.17.0-test.50 | ❌     | default |                       |         |                               |     
 | Registry Overview For Charts                        |
+---+---------------+---------------+--------+--------+
| # | HELM CHART    | CHART VERSION | HARBOR | IMPORT |
+---+---------------+---------------+--------+--------+
| 0 | charts/sparta | 24.16.7       | ✅     | ❌     |
+---+---------------+---------------+--------+--------+
|   |               |               |        | 0      |
+---+---------------+---------------+--------+--------+
```
Helmper detects that 24.16.7 is not the latest version(although it's the latest production version), but any other version than '0.0.0>0' in helmper.yaml produces nothing. 
No helm chart 24.17.0-test.50 is uploaded, nor any images is imported.

```
verbose: true
import:
  enabled: true
charts:
  - name: sparta
    version: ">0.0.0-0"
    repo:
      name: sparta
      url: oci://reg.test.com/sparta/helm-charts/sparta
registries:
- name: harbor
  url: harbor.test.com
  insecure: true
```
Is this a bug or did I made a mistake?
