### ISSUE TITLE
[feat] Manipulate chart destination based on source

### ISSUE THREAD

**Issue by sboschman** [ChristofferNissen/helmper#153]
Same request as in #115 but for the Chart destination instead of the image destination, basically to overrule the default `charts/` path with a per chart based path.

Don't know if this idea breaks stuff, but using the `charts[].repo.name` field instead of the fixed `charts` path would work for me.

Docs section suggestion:
> Helm Charts will be placed under `charts/{chart_name}`, and images will be placed directly in the regsitry root `/`.

> Optionally, if you specify `registry[].sourcePrefix=true`, Helm charts will be placed under `{chart_repo_name}/{chart_name}` and images will be placed under a path obtained from the source registry name ...

Example:
```yaml
charts:
  - name: loki
    version: 5.38.0
    repo:
      name: grafana
      url: https://grafana.github.io/helm-charts/
registries:
  - name: registry
    url: 0.0.0.0:5000
    sourcePrefix: true
```

Which would result in the registry path`/v2/grafana/loki/manifests/5.38.0` instead of `/v2/charts/loki/manifests/5.38.0` for the loki chart.
