### ISSUE TITLE
OCI registry as source for Helm Charts is not working

### ISSUE THREAD

**Issue by haarchri** [ChristofferNissen/helmper#40]
want to use helmper - the helm-chart in in gcp container registry - but the endpoint is **oci://**

```
helm -n xxx upgrade --install xx \
  oci://us-west1-docker.pkg.dev/haarchri/xxx \
  --version "1.2.3" \
  --wait
```

i get the following error: 

```
k8s_version: 1.27.9
import:
  enabled: true
charts:
- name: xxx
  version: 1.4.0
  repo:
    name: xxx
    url: https://us-west1-docker.pkg.dev/haarchri/xxx/
registries:
- name: registry
  url: 0.0.0.0:5002
  insecure: true
  plainHTTP: true
```

`is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile"}`

if i try with:

```
k8s_version: 1.27.9
import:
  enabled: true
charts:
- name: xxx
  version: 1.4.0
  repo:
    name: xxx
    url: oci://us-west1-docker.pkg.dev/haarchri/xxx/
registries:
- name: registry
  url: 0.0.0.0:5002
  insecure: true
  plainHTTP: true
```

`oci://us-west1-docker.pkg.dev/haarchri/xxx/\" is not a valid chart repository or cannot be reached: object required"}`
