### ISSUE TITLE
could not find protocol handler for

### ISSUE THREAD

**Issue by haarchri** [ChristofferNissen/helmper#41]
after a few tries for gke registry logins - i get only the following issue:

```
helmper --f sync.yaml

 _         _
| |_  ___ | | _____  ___  ___  ___
|   || -_|| ||     || . || -_||  _|
|_|_||___||_||_|_|_||  _||___||_|
                    |_|
version 0.1.4 (commit 2999f891aba1adbe55b8365115f84492b99c1376, built at 2024-05-30T12:19:03Z)

{"time":"2024-06-11T01:18:16.494742+03:00","level":"ERROR","msg":"could not find protocol handler for: "}
```

```
k8s_version: 1.27.9
import:
  enabled: true
charts:
- name: prometheus
  version: 25.8.0
  valuesFile: /workspace/in/values/prometheus/values.yaml # (Optional)
  repo:
    name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts/
registries:
- name: registry
  url: 0.0.0.0:5002
  insecure: true
  plainHTTP: true
```

```
 docker ps
CONTAINER ID   IMAGE        COMMAND                  CREATED         STATUS         PORTS                    NAMES
9a3cfa086576   registry:2   "/entrypoint.sh /etc…"   2 minutes ago   Up 2 minutes   0.0.0.0:5002->5000/tcp   registry
```
