### ISSUE TITLE
[feat] add capability to use registry mirrors

### ISSUE THREAD

**Issue by ChristofferNissen** [ChristofferNissen/helmper#67]
Add option to use mirrors

Suggested syntax

```yaml
mirrors:
- registry: docker.io
  mirror: example.azurecr.io/docker/
  insecure: false
  plainHTTP: false
```
