### ISSUE TITLE
Semver error when .charts[].repo.name not specified

### ISSUE THREAD

**Issue by abohne** [ChristofferNissen/helmper#90]
If you add a chart to the `charts` section, but do not specify a name, you receive the following error:
```bash
version is not semver. skipping this version
```

helmper.yaml
```yaml
k8s_version: "1.27"
import:
  enabled: true
charts:
- name: kiali-operator
  version: "1.87.0"
  repo:
    url: https://kiali.org/helm-charts
```

This error is very misleading.
