### ISSUE TITLE
getting signer: reading key: loading URL: unrecognized scheme: awskms://

### ISSUE THREAD

**Issue by abohne** [ChristofferNissen/helmper#92]
When trying to enable cosign using an AWS KMS key,  the following error is generated:
```
{"time":"2024-08-22T12:32:47.574645-04:00","level":"ERROR","msg":"getting signer: reading key: loading URL: unrecognized scheme: awskms://"}
```

My helmper.yaml looks like
```yaml
k8s_version: "1.27"
import:
  enabled: true
  architecture: "linux/amd64"
  cosign:
    enabled: true
    keyRef: awskms:///alias/mykey
charts:
- name: kiali-operator
  version: "1.87.0"
  repo:
    name: kiali
    url: https://kiali.org/helm-charts
```
